
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: janus-backend
    container_name: janus-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: janus-app
    container_name: janus-app
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - ./app/models:/app/app/models
      - ./docker:/app/docker:ro
    restart: always
