# 使用轻量 Python 镜像
FROM python:3.12-slim

# 设置工作目录
WORKDIR /Javelin

RUN apt-get update && apt-get install -y tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
    
# 拷贝网站代码和模板
COPY web/ /Javelin/web/
RUN pip install --no-cache-dir -r /Javelin/web/requirements.txt
# 拷贝共享配置与模块
COPY config/ /Javelin/config/
COPY utils/ /Javelin/utils/

# 设置环境变量
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Flask 端口
EXPOSE 5000

# 启动 Flask
CMD ["python", "/Javelin/web/Javelin.py"]